config/routes.rb
Rails.application.routes.draw do
  resources :promocaos
  resources :notificacaos
  root to: 'visitors#index'

  namespace :api do
   resources :push_notification, only: [:index]
   resources :promotion, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notificacao.rb
class Notificacao < ApplicationRecord
end

app/models/promocao.rb
class Promocao < ApplicationRecord
    
end

app/controllers/api/promotion_controller.rb
class Api::PromotionController < ApplicationController

  def index
    begin
      @beacon = Promocao.find_by(beacon_id: params[:beacon_id].gsub(/[^0-9]/, ''))
      if @beacon.present?
        render json: @beacon, status: :ok
      else
        render json: "Beacon não encontrado".to_json, status: :ok
      end
    rescue
      render status: :not_found, json: "Beacon não encontrado".to_json
    end
  end

end

app/controllers/api/push_notification_controller.rb
class Api::PushNotificationController < ApplicationController

  def index
    begin
      @beacon = Notificacao.find_by(beacon_id: params[:beacon_id].gsub(/[^0-9]/, ''))
      if @beacon.present?
        render json: @beacon, status: :ok
      else
        render json: "Beacon não encontrado".to_json, status: :ok
      end
    rescue
      render status: :not_found, json: "Beacon não encontrado".to_json
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notificacaos_controller.rb
class NotificacaosController < ApplicationController
  before_action :set_notificacao, only: [:show, :edit, :update, :destroy]

  # GET /notificacaos
  # GET /notificacaos.json
  def index
    @notificacaos = Notificacao.all
  end

  # GET /notificacaos/1
  # GET /notificacaos/1.json
  def show
  end

  # GET /notificacaos/new
  def new
    @notificacao = Notificacao.new
  end

  # GET /notificacaos/1/edit
  def edit
  end

  # POST /notificacaos
  # POST /notificacaos.json
  def create
    @notificacao = Notificacao.new(notificacao_params)

    respond_to do |format|
      if @notificacao.save
        format.html { redirect_to @notificacao, notice: 'Notificacao was successfully created.' }
        format.json { render :show, status: :created, location: @notificacao }
      else
        format.html { render :new }
        format.json { render json: @notificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notificacaos/1
  # PATCH/PUT /notificacaos/1.json
  def update
    respond_to do |format|
      if @notificacao.update(notificacao_params)
        format.html { redirect_to @notificacao, notice: 'Notificacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @notificacao }
      else
        format.html { render :edit }
        format.json { render json: @notificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notificacaos/1
  # DELETE /notificacaos/1.json
  def destroy
    @notificacao.destroy
    respond_to do |format|
      format.html { redirect_to notificacaos_url, notice: 'Notificacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notificacao
      @notificacao = Notificacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notificacao_params
      params.require(:notificacao).permit(:titulo, :mensagem, :beacon_id)
    end
end

app/controllers/promocaos_controller.rb
class PromocaosController < ApplicationController
  before_action :set_promocao, only: [:show, :edit, :update, :destroy]

  # GET /promocaos
  # GET /promocaos.json
  def index
    @promocaos = Promocao.all
  end

  # GET /promocaos/1
  # GET /promocaos/1.json
  def show
  end

  # GET /promocaos/new
  def new
    @promocao = Promocao.new
  end

  # GET /promocaos/1/edit
  def edit
  end

  # POST /promocaos
  # POST /promocaos.json
  def create
    @promocao = Promocao.new(promocao_params)

    respond_to do |format|
      if @promocao.save
        format.html { redirect_to @promocao, notice: 'Promocao was successfully created.' }
        format.json { render :show, status: :created, location: @promocao }
      else
        format.html { render :new }
        format.json { render json: @promocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promocaos/1
  # PATCH/PUT /promocaos/1.json
  def update
    respond_to do |format|
      if @promocao.update(promocao_params)
        format.html { redirect_to @promocao, notice: 'Promocao was successfully updated.' }
        format.json { render :show, status: :ok, location: @promocao }
      else
        format.html { render :edit }
        format.json { render json: @promocao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promocaos/1
  # DELETE /promocaos/1.json
  def destroy
    @promocao.destroy
    respond_to do |format|
      format.html { redirect_to promocaos_url, notice: 'Promocao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promocao
      @promocao = Promocao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promocao_params
      params.require(:promocao).permit(:titulo, :mensagem, :imagem, :beacon_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notificacaos_helper.rb
module NotificacaosHelper
end

app/helpers/promocaos_helper.rb
module PromocaosHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Beacon Server" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Beacon Server" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/notificacaos/_form.html.erb
<%= form_with(model: notificacao, local: true) do |form| %>
  <% if notificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notificacao.errors.count, "error") %> prohibited this notificacao from being saved:</h2>

      <ul>
      <% notificacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :mensagem %>
    <%= form.text_area :mensagem %>
  </div>

  <div class="field">
    <%= form.label :beacon_id %>
    <%= form.text_field :beacon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notificacaos/edit.html.erb
<h1>Editing Notificacao</h1>

<%= render 'form', notificacao: @notificacao %>

<%= link_to 'Show', @notificacao %> |
<%= link_to 'Back', notificacaos_path %>

app/views/notificacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notificacaos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Mensagem</th>
      <th>Beacon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notificacaos.each do |notificacao| %>
      <tr>
        <td><%= notificacao.titulo %></td>
        <td><%= notificacao.mensagem %></td>
        <td><%= notificacao.beacon_id %></td>
        <td><%= link_to 'Show', notificacao %></td>
        <td><%= link_to 'Edit', edit_notificacao_path(notificacao) %></td>
        <td><%= link_to 'Destroy', notificacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notificacao', new_notificacao_path %>

app/views/notificacaos/new.html.erb
<h1>New Notificacao</h1>

<%= render 'form', notificacao: @notificacao %>

<%= link_to 'Back', notificacaos_path %>

app/views/notificacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @notificacao.titulo %>
</p>

<p>
  <strong>Mensagem:</strong>
  <%= @notificacao.mensagem %>
</p>

<p>
  <strong>Beacon:</strong>
  <%= @notificacao.beacon_id %>
</p>

<%= link_to 'Edit', edit_notificacao_path(@notificacao) %> |
<%= link_to 'Back', notificacaos_path %>

app/views/promocaos/_form.html.erb
<%= form_with(model: promocao, local: true) do |form| %>
  <% if promocao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promocao.errors.count, "error") %> prohibited this promocao from being saved:</h2>

      <ul>
      <% promocao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :mensagem %>
    <%= form.text_area :mensagem %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.text_field :imagem %>
  </div>

  <div class="field">
    <%= form.label :beacon_id %>
    <%= form.text_field :beacon_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promocaos/edit.html.erb
<h1>Editing Promocao</h1>

<%= render 'form', promocao: @promocao %>

<%= link_to 'Show', @promocao %> |
<%= link_to 'Back', promocaos_path %>

app/views/promocaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Promocaos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Mensagem</th>
      <th>Imagem</th>
      <th>Beacon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promocaos.each do |promocao| %>
      <tr>
        <td><%= promocao.titulo %></td>
        <td><%= promocao.mensagem %></td>
        <td><%= promocao.imagem %></td>
        <td><%= promocao.beacon_id %></td>
        <td><%= link_to 'Show', promocao %></td>
        <td><%= link_to 'Edit', edit_promocao_path(promocao) %></td>
        <td><%= link_to 'Destroy', promocao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promocao', new_promocao_path %>

app/views/promocaos/new.html.erb
<h1>New Promocao</h1>

<%= render 'form', promocao: @promocao %>

<%= link_to 'Back', promocaos_path %>

app/views/promocaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @promocao.titulo %>
</p>

<p>
  <strong>Mensagem:</strong>
  <%= @promocao.mensagem %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @promocao.imagem %>
</p>

<p>
  <strong>Beacon:</strong>
  <%= @promocao.beacon_id %>
</p>

<%= link_to 'Edit', edit_promocao_path(@promocao) %> |
<%= link_to 'Back', promocaos_path %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>